### ISSUE TITLE
better nick system

### ISSUE THREAD

**Issue by efor89** [jasonwynn10/Nicknames#5]
hi jason
can you make the plugin more like this one https://github.com/tim03we/AdvancedNick??
this plugin chang the pureperm rank and the name i rewrith it and it work rly good but the rank chang is not so good!
so my question can you chang the chat format so that in chat all see me as a new player with the default rank default color default tag with rnd nick or my own nick and with bedrockclan support that the clan name is not show too?

**Comment by jasonw4331** [comment]
Test the latest release please

**Comment by efor89** [comment]
i test it but it dont chang the chat format it show the clanname, rank and rank color in chat.

can you do it like this

![Screenshot (47)](https://user-images.githubusercontent.com/67799203/97852750-7166e280-1cf7-11eb-9592-14a1da8d94ee.png)

**Comment by efor89** [comment]
but in the moment the nick plugin give me the nick rank and with this rank i dont have my real rank permisson

**Comment by efor89** [comment]
and my question is can you do it like this without chang the pureperm rank
only with chang chatformat?

**Comment by jasonw4331** [comment]
Ohhhh, I see what you want now. This plugin is only a nickname plugin. It is not designed as a disguise plugin.
